name: CI

on:
  push:
    branches: [master]
  pull_request:

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install compiler tools 
        run: |
          sudo apt-get update
          sudo apt-get install pkg-config uuid-dev cmake build-essential
          sudo apt install gcc-8 g++-8
          sudo apt install nvidia-cuda-toolkit
          sudo apt install nvidia-cuda-dev 

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: setup ANTLR
        run: | 
          sudo wget https://www.antlr.org/download/antlr-4.10-complete.jar

      - name: Compile
        run: |
          cmake -B build/ -D CMAKE_CUDA_ARCHITECTURES=75
          cmake --build build/  

      - name: Run CPU analysis
        run: | 
          build/analyzer --cpu prog.sc

      - name: Run multi-taint CPU analysis
        run: |
          build/analyzer --cpu --multi prog.sc

      - name: Run cpu capable test
        run: | 
          build/test-cpu  