name: CI

on:
  push:
    branches: [ci-workflow]
  pull_request:

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install compiler tools 
        run: |
          sudo apt-get update
          sudo apt-get install pkg-config uuid-dev cmake build-essential

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: NiccoMlt/setup-antlr4@v0.0.6

      - uses: Jimver/cuda-toolkit@v0.2.5
        id: cuda-toolkit

      - name: Compile
        run: |
          cmake -B build/ -D ANTLR_EXECUTABLE=$Antlr4ToolPath -D CMAKE_CUDA_ARCHITECTURES=75
          cmake --build build/  

