name: CI

on:
  push:
    branches: [ci-workflow]
  pull_request:

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install compiler tools 
        run: |
          sudo apt-get update
          sudo apt-get install pkg-config uuid-dev cmake build-essential

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: setup ANTLR
        run: | 
          cd /usr/local/lib
          sudo wget https://www.antlr.org/download/antlr-4.9.2-complete.jar

      - uses: Jimver/cuda-toolkit@v0.2.5
        id: cuda-toolkit

      - name: Compile
        run: |
          git submodule update --init --recursive
          cmake -B build/ -D ANTLR_EXECUTABLE="/usr/local/lib" -D CMAKE_CUDA_ARCHITECTURES=75
          cmake --build build/  

